#!/bin/bash -ex
#
# Build AWS Lambda function ZIP file and upload to S3
#
# Usage: ./build-upload-aws-lambda-function S3BUCKET S3KEY [HUGOVERSION]
#
# For example:
# ./build-upload-aws-lambda-function run.alestic.com lambda/aws-lambda-site-generator-hugo-0.17.zip 0.17
#

s3bucket=${1:?Specify target S3 bucket name}
s3key=${2:?Specify target S3 key}
target=s3://$s3bucket/$s3key
hugo_version="${3:0.36}"

tmpdir=$(mktemp -d /tmp/lambda-XXXXXX)
zipfile=$tmpdir/lambda.zip

# Add AWS Lambda function file to ZIP file
zip -r9 $zipfile index.py

# Download and add Hugo binary executable to ZIP file
download_url="https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.tar.gz"

(
 cd $tmpdir
 wget -qO hugo.tar.gz $download_url
 tar xvzf hugo.tar.gz
 zip -r9 $zipfile hugo
)

# Upload AWS Lambda function ZIP file to S3
aws s3 cp --acl public-read $zipfile $target

# Clean up
rm -r $tmpdir
